import type { TrendItem } from '../types';

export const INITIAL_TRENDS: TrendItem[] = [
  {
    id: 'trend-1',
    title: 'Gaji Remote USD Pekerja Tech Indonesia',
    titleEn: 'USD Remote Tech Salary Trends in Indonesia',
    category: 'business',
    heatScore: 98,
    growthRate: '+420%',
    searchVolume: '100K+ penelusuran',
    platform: 'Google Trends',
    sentiment: 'positive',
    summary: 'Lonjakan penelusuran mengenai cara dapat pekerjaan remote berbayar Dolar AS bagi developer, designer, dan marketer Indonesia.',
    targetAudience: 'Software Engineer, UI/UX Designer, Freelancer, Gen-Z Professional',
    hashtags: ['#RemoteWorkIndo', '#GajiUSD', '#KerjaRemote', '#TechCareer'],
    relatedKeywords: ['upwork indonesia', 'platform kerja remote', 'tukar rupiah paypal', 'kontrak kerja US'],
    updatedAt: '10 menit yang lalu',
    isHot: true,
    isRising: true,
  },
  {
    id: 'trend-2',
    title: 'Solana & AI Agent Meme Coins Surge',
    titleEn: 'Solana AI Agent Crypto Trends',
    category: 'crypto',
    heatScore: 94,
    growthRate: '+280%',
    searchVolume: '75K+ penelusuran',
    platform: 'Twitter/X',
    sentiment: 'controversial',
    summary: 'Diskusi hangat seputar koin crypto berbasis AI Agent & autonomous trading bot di jaringan Solana.',
    targetAudience: 'Crypto Traders, Web3 Enthusiasts, Algorithmic Traders',
    hashtags: ['#CryptoIndo', '#SolanaAI', '#AIAgent', '#Web3'],
    relatedKeywords: ['solana dex', 'raydium bot', 'ai crypto token', 'pump fun solana'],
    updatedAt: '15 menit yang lalu',
    isHot: true,
    isRising: true,
  },
  {
    id: 'trend-3',
    title: 'Cursor AI & Claude 3.6 for Web Development',
    titleEn: 'Vibe Coding with Cursor & Claude AI',
    category: 'tech',
    heatScore: 92,
    growthRate: '+310%',
    searchVolume: '50K+ penelusuran',
    platform: 'Reddit',
    sentiment: 'positive',
    summary: 'Tren "Vibe Coding" di mana developer membangun aplikasi web penuh dalam hitungan jam menggunakan AI Agent & LLM modern.',
    targetAudience: 'Frontend Dev, Fullstack Dev, Startup Founders, Solopreneurs',
    hashtags: ['#VibeCoding', '#CursorAI', '#Claude36', '#WebDev', '#BuildInPublic'],
    relatedKeywords: ['cara pakenya cursor ai', 'nextjs ai template', 'prompts coding', 'antigravity ide'],
    updatedAt: '25 menit yang lalu',
    isHot: true,
    isRising: true,
  },
  {
    id: 'trend-4',
    title: 'Perang Diskon E-Commerce & Affiliate Shopee/TikTok',
    titleEn: 'E-Commerce Commission Wars & Live Shopping',
    category: 'viral',
    heatScore: 89,
    growthRate: '+190%',
    searchVolume: '120K+ penelusuran',
    platform: 'TikTok',
    sentiment: 'positive',
    summary: 'Strategi afiliasi live streaming yang menghasilkan puluhan juta per bulan dengan modal HP.',
    targetAudience: 'Affiliate Marketer, Ibu Rumah Tangga, Mahasiswa, Content Creator',
    hashtags: ['#TikTokAffiliate', '#ShopeeHaul', '#KomisiTinggi', '#CuanDariRumah'],
    relatedKeywords: ['cara daftar affiliate', 'sampel gratis tiktok', 'konten jualan fyp'],
    updatedAt: '40 menit yang lalu',
    isHot: false,
    isRising: true,
  },
  {
    id: 'trend-5',
    title: 'Game Handheld Retro & Steam Deck OLED Mod',
    titleEn: 'Retro Gaming Handheld Popularity',
    category: 'gaming',
    heatScore: 85,
    growthRate: '+140%',
    searchVolume: '35K+ penelusuran',
    platform: 'Google Trends',
    sentiment: 'neutral',
    summary: 'Tingginya minat konsol game portable murah seperti Anbernic, Miyoo Mini, dan custom Steam Deck untuk nostalgia.',
    targetAudience: 'Gamers, Nostalgia Millenials, Tech Collectors',
    hashtags: ['#RetroGaming', '#SteamDeckIndo', '#HandheldConsole', '#GamingID'],
    relatedKeywords: ['emulator ps2 android', 'rekomendasi handheld murah', 'game retro indonesia'],
    updatedAt: '1 jam yang lalu',
    isHot: false,
    isRising: false,
  },
  {
    id: 'trend-6',
    title: 'Gaya Hidup Frugal Living & Investasi SBR / Reksadana',
    titleEn: 'Frugal Living and Retail Bond Investment',
    category: 'lifestyle',
    heatScore: 88,
    growthRate: '+210%',
    searchVolume: '60K+ penelusuran',
    platform: 'News RSS',
    sentiment: 'positive',
    summary: 'Gen-Z dan Millennials berbondong-bondong mengadopsi Frugal Living untuk capai Financial Independence.',
    targetAudience: 'First Jobbers, Gen-Z, Young Married Couples',
    hashtags: ['#FrugalLiving', '#FinancialFreedom', '#InvestasiMuda', '#SBR013'],
    relatedKeywords: ['saham vs reksadana', 'cara hemat gaji 5 juta', 'dana darurat', 'bibit app'],
    updatedAt: '2 jam yang lalu',
    isHot: false,
    isRising: true,
  },
  {
    id: 'trend-7',
    title: 'SaaS Tanpa Koding (No-Code AI Automation)',
    titleEn: 'No-Code AI Automation for Small Businesses',
    category: 'tech',
    heatScore: 91,
    growthRate: '+350%',
    searchVolume: '45K+ penelusuran',
    platform: 'Reddit',
    sentiment: 'positive',
    summary: 'Agensi AI Automation membludak menawarkan otomatisasi WhatsApp, Make.com, & N8N ke UMKM lokal.',
    targetAudience: 'Agency Owners, Freelancers, Business Consultants',
    hashtags: ['#AIAutomation', '#MakeCom', '#N8N', '#NoCodeSaaS'],
    relatedKeywords: ['whatsapp bot otomatis', 'n8n workflow tutorial', 'jasa otomatisasi bisnis'],
    updatedAt: '3 jam yang lalu',
    isHot: true,
    isRising: true,
  },
  {
    id: 'trend-8',
    title: 'Kopi Susu Gula Aren vs Artisan Specialty Coffee',
    titleEn: 'Artisan Specialty Coffee Wave',
    category: 'lifestyle',
    heatScore: 78,
    growthRate: '+95%',
    searchVolume: '80K+ penelusuran',
    platform: 'TikTok',
    sentiment: 'neutral',
    summary: 'Pergeseran tren penikmat kopi dari sekadar kopi susu murah ke slow bar V60 & biji kopi lokal single origin.',
    targetAudience: 'Coffee Enthusiasts, Barista, Cafe Owners',
    hashtags: ['#KopiIndonesia', '#SpecialtyCoffee', '#BaristaLife', '#SlowBar'],
    relatedKeywords: ['biji kopi aceh gayo', 'alat kopi manual brew', 'rekomendasi cafe aesthetic'],
    updatedAt: '4 jam yang lalu',
    isHot: false,
    isRising: false,
  }
];
